name: publish

on: [push]

jobs:
  publish-base-srcds-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch


    - name: Build base-srcds image
      run: |
        docker build . --tag ghcr.io/leighmacdonald/base-srcds:${{ steps.extract_branch.outputs.branch }}

    - name: Publish base-srcds image
      run: |
        docker push gchr.io/leighmacdonald/base-srcds:${{ steps.extract_branch.outputs.branch }}
